name: Build & Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  redeployment:
    runs-on: ubuntu-latest
    steps:
     - name: execute remote shh commands using password
       uses: actions/checkout@v4
       with:
          host: ${{secrets.OCEANIP}}
          key: ${{secrets.OCEAN_SSH}}
          username: ${{secrets.OCEAN_USERNAME}}
          password: ${{secrets.OCEAN_PASS}}
        
          script:
            cd Repositories
            cd Django_Project_Udemy_2
            docker compose down && docker compose rm
            git pull
            docker compose build
            docker compose up -d
            docker exec -it django_project_udemy_2-backend-1 bash
            python manage.py makemigrations
            python manage.py migrate
            exit
