name: Build & Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  redeployment:
    runs-on: ubuntu-latest
    steps:
     - name: execute remote shh commands using password
       uses: appleboy/ssh-action@master
       with:
          host: ${{secrets.OCEANIP}}
          username: ${{secrets.OCEAN_USERNAME}}
          password: ${{secrets.OCEAN_PASS}}
          script: whoami
